image: Visual Studio 2019

install:
  - ps: Get-Content -Path .\appveyor_vsix.ps1 -Raw | iex
  - NuGet sources Add -Name Roslyn -Source https://dotnet.myget.org/F/roslyn/api/v3/index.json

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement SwitchStartupProject\Properties\AssemblyInfoVersion.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
