image: Visual Studio 2015

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/13thirteen/ExtensionScripts/displayreadmefrombitbucketrepos/AppVeyor/vsix.ps1") | iex

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: Vsix-TokenReplacement SwitchStartupProject\Properties\AssemblyInfoVersion.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
